language: c

sudo: required

before_install:
  - cd cascade
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script:
  - ./travis-tool.sh run_tests
  - cd ..
  - Rscript -e 'options(repos=c(CRAN="'"${CRAN}"'")); install.packages("dplyr"); install.packages("FME"); install.packages("reshape2"); install.packages("readr")'
  - Rscript -e 'library(FME); library(FME); testthat::test_dir("CascadeDashboard/tests")'


after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  slack: dide-hiv:lZajIW2gCbXMYVgXkp1Bu1ii
  email:
    on_success: change
    on_failure: change
