# Check this in a 'serverhead.R' and source eventually
# source("server/serverHead.R", local = TRUE)
library(shiny)
library(ggplot2)
library(dplyr)
library(deSolve)
library(gridExtra)
library(DT)
library(shinyjs)
library(V8)
library(googlesheets)
library(RColorBrewer)
library(scales)
library(ggthemes)
library(grid)
# devtools::install_github("jackolney/WhoCascade/cascade", ref = "dashboard")
library(cascade)

shinyServer(function(input, output, session) source("server/app.R", local = TRUE))
