tabItem(tabName = "opt-parameter",
    column(width = 8,
        shinyjs::useShinyjs(),
        id = "optimisation-panel",
        box(width = NULL,
            height = '100%',
            status = "primary",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "HIV-Testing",

            tags$h4("Status Quo"),
            "At current levels, the model predicts that between 2015 and 2020, assuming ceteris paribus,
            the total number of individuals diagnosed with HIV will be:",
            p(""),
            uiOutput("opt_rho_baseline"),

            tags$h4("Intervention"),
            "However, by simulating an HIV testing intervention, we can increase testing such that an
            additional number of individuals are diagnosed by 2020. By adjusting the value below,
            the testing rate is varied between the status quo (no intervention) and the status quo
            multiplied by the intervention rate factor (maximum intervention).",
            p(""),
            numericInput(inputId = "opt_rho_factor", label = "Intervention rate factor:", value = 10, min = 0, max = 100, step = 1, width = "100%"),
            "The total number of additional diagnoses made between 2015 and 2015 will be:",
            p(""),
            uiOutput("opt_rho_max")

            # uiOutput("UI_optP_rhoRange"),
            # tableOutput("optParTable_Rho")
        ),
        box(width = NULL,
            height = '100%',
            status = "primary",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "Linkage",
            uiOutput("UI_optP_qRange"),
            tableOutput("optParTable_Q")
        ),
        box(width = NULL,
            height = '100%',
            status = "primary",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "Pre-ART Retention (kappa)",
            uiOutput("UI_optP_kappaRange"),
            tableOutput("optParTable_Kappa")
        ),
        box(width = NULL,
            height = '100%',
            status = "primary",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "Treatment Initiation",
            uiOutput("UI_optP_gammaRange"),
            tableOutput("optParTable_Gamma")
        ),
        box(width = NULL,
            height = '100%',
            status = "primary",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "Adherence",
            uiOutput("UI_optP_sigmaRange"),
            tableOutput("optParTable_Sigma")
        ),
        box(width = NULL,
            height = '100%',
            status = "primary",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "ART Retention",
            uiOutput("UI_optP_omegaRange"),
            tableOutput("optParTable_Omega")
        )
    ),
    column(width = 4,
        box(width = NULL,
            status = "warning",
            solidHeader = TRUE,
            title = "Parameter Selection",
            p("The optimisation algorithm takes six model parameters representing six hypothetical interventions and simulates the cost and impact of all permutations."),
            helpText("For each intervention, select the number of parameter values to simulate and set the range of rates to sample from (rates are uniformally distributed within this range).
                The parameter values for each intervention are then displayed in the corresponding tables."),
            numericInput(inputId = "optimParamLength",   label = "Number of parameter values to sample:", value = 4, min = 0, max = 10, step = 1, width = "100%"),
            bsButton("resetSliders", label = "RESET SLIDERS", block = TRUE, style = "danger"),
            p(" "),
            helpText("Below is the number of iterations the model will simulate along with the estimated time to completion. Hit the 'OPTIMISE' button to begin the simulation. Note the progress bar
                at the top of the screen, and the run number and elapsed time on the top right. Please wait until the optimisation algorithm has completed the below bar has turned green before proceeding to the results tab."),
            p(" "),
            tableOutput("optIterationTable")
        ),
        bsButton(inputId = "PREV_optParam", label = "Return", style = "primary", size = "large", block = TRUE, icon = icon("backward", class = "fa-lg fa-fw", lib = "font-awesome"))
    )
)
