# devtools::install_github("shinyTable", "trestletech")
library(DT)
library(ggplot2)
library(shiny)
library(shinyBS)
library(shinydashboard)
library(shinyjs)
library(shinyTable)
library(shinythemes)
library(V8)
