CountryList <- c(
    "Brazil",
    "Cambodia",
    "Cameroon",
    "China",
    "Cote d'Ivoire",
    "DRC",
    "Ethiopia",
    "Haiti",
    "India",
    "Indonesia",
    "Jamaica",
    "Kenya",
    "Malawi",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Nigeria",
    "Pakistan",
    "Philippines",
    "Russia",
    "South Africa",
    "South Sudan",
    "Tanzania",
    "Thailand",
    "Uganda",
    "Ukraine",
    "Vietnam",
    "Zambia",
    "Zimbabwe"
)

LeafletCountryList <- c(
    "Brazil",
    "Cambodia",
    "Cameroon",
    "China",
    "C<f4>te d'Ivoire",
    "Dem. Rep. Congo",
    "Ethiopia",
    "Haiti",
    "India",
    "Indonesia",
    "Jamaica",
    "Kenya",
    "Malawi",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Nigeria",
    "Pakistan",
    "Philippines",
    "Russia",
    "South Africa",
    "S. Sudan",
    "Tanzania",
    "Thailand",
    "Uganda",
    "Ukraine",
    "Vietnam",
    "Zambia",
    "Zimbabwe",
    "C\364te d'Ivoire"
)

SourceList <- data.frame(
    name = c(
        "Please select source...",
        "Case based surveillance - nationally representative",
        "Case based surveillance with caveats - e.g. not nationally representative",
        "Estimate - source data not clear",
        "GARPR  / Spectrum",
        "Mathematical model - nationally representative",
        "Mathematical model - non-nationally representative",
        "Nationally representative study  - cohort / cross-sectional",
        "Program data - adjusted (e.g. for under-reporting) and/or large geographical coverage",
        "Program data - not adjusted and/or small geographical coverage",
        "Sub-national study",
        "Vital statistics"
    ),
    weight = c(
        "NULL",
        "green",
        "amber",
        "red",
        "green",
        "amber",
        "red",
        "green",
        "amber",
        "red",
        "amber",
        "green"
    )
)

SourceListTable <- data.frame(
    Source = c(
        "Case based surveillance - nationally representative",
        "Case based surveillance with caveats - e.g. not nationally representative",
        "Estimate - source data not clear",
        "GARPR  / Spectrum",
        "Mathematical model - nationally representative",
        "Mathematical model - non-nationally representative",
        "Nationally representative study  - cohort / cross-sectional",
        "Program data - adjusted (e.g. for under-reporting) and/or large geographical coverage",
        "Program data - not adjusted and/or small geographical coverage",
        "Sub-national study",
        "Vital statistics"
    ),
    Weight = c(
        "green",
        "amber",
        "red",
        "green",
        "amber",
        "red",
        "green",
        "amber",
        "red",
        "amber",
        "green"
    )
)

YearList <- seq(2010, 2015, 1)

ErrorList <- as.character(seq(from = 0.1, to = 5, by = 0.1))

VariableNames <- c(
    "UnDx_500",
    "UnDx_350500",
    "UnDx_250350",
    "UnDx_200250",
    "UnDx_100200",
    "UnDx_50100",
    "UnDx_50",
    "Dx_500",
    "Dx_350500",
    "Dx_250350",
    "Dx_200250",
    "Dx_100200",
    "Dx_50100",
    "Dx_50",
    "Care_500",
    "Care_350500",
    "Care_250350",
    "Care_200250",
    "Care_100200",
    "Care_50100",
    "Care_50",
    "PreLtfu_500",
    "PreLtfu_350500",
    "PreLtfu_250350",
    "PreLtfu_200250",
    "PreLtfu_100200",
    "PreLtfu_50100",
    "PreLtfu_50",
    "Tx_Na_500",
    "Tx_Na_350500",
    "Tx_Na_250350",
    "Tx_Na_200250",
    "Tx_Na_100200",
    "Tx_Na_50100",
    "Tx_Na_50",
    "Tx_A_500",
    "Tx_A_350500",
    "Tx_A_250350",
    "Tx_A_200250",
    "Tx_A_100200",
    "Tx_A_50100",
    "Tx_A_50",
    "Ltfu_500",
    "Ltfu_350500",
    "Ltfu_250350",
    "Ltfu_200250",
    "Ltfu_100200",
    "Ltfu_50100",
    "Ltfu_50",
    "NewInf",
    "HivMortality",
    "NaturalMortality",
    "N",
    "ART",
    "UnDx",
    "Dx",
    "Care",
    "Tx",
    "Vs",
    "Ltfu",
    "NaturalMortalityProp",
    "HivMortalityProp",
    "NewInfProp",
    "Dx_Cost",
    "Linkage_Cost",
    "Annual_Care_Cost",
    "Annual_ART_Cost",
    "TotalCost",
    "cd4_500",
    "cd4_350500",
    "cd4_250350",
    "cd4_200250",
    "cd4_100200",
    "cd4_50100",
    "cd4_50",
    "DALY"
)

InterventionList <- c("Testing", "Linkage", "Pre-ART Retention", "Initiation", "Adherence", "ART Retention")
