tabItem(tabName = "opt-parameter",
    column(width = 8,
        shinyjs::useShinyjs(),
        id = "optimisation-panel",
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "HIV-Testing (rho)",
            helpText("by varying diagnosis rate, rho"),
            uiOutput("UI_optP_rhoLength"),
            uiOutput("UI_optP_rhoRange"),
            tableOutput("optParTable_Rho")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "Linkage (q)",
            helpText("by varying proportion of diagnosed individuals that link to care, q:"),
            uiOutput("UI_optP_qLength"),
            uiOutput("UI_optP_qRange"),
            tableOutput("optParTable_Q")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "Pre-ART Retention (kappa)",
            helpText("by varying pre-ART dropout rate, kappa"),
            uiOutput("UI_optP_kappaLength"),
            uiOutput("UI_optP_kappaRange"),
            tableOutput("optParTable_Kappa")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "Treatment Initiation (gamma)",
            helpText("by varying ART initiation rate, gamma"),
            uiOutput("UI_optP_gammaLength"),
            uiOutput("UI_optP_gammaRange"),
            tableOutput("optParTable_Gamma")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "Adherence (sigma)",
            helpText("by varying rate at which patients not adhering to treatment start to adhere, sigma"),
            uiOutput("UI_optP_sigmaLength"),
            uiOutput("UI_optP_sigmaRange"),
            tableOutput("optParTable_Sigma")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            collapsible = TRUE,
            collapsed = FALSE,
            title = "ART Retention (omega)",
            helpText("by varying rate at which patients are lost from ART care, omega"),
            uiOutput("UI_optP_omegaLength"),
            uiOutput("UI_optP_omegaRange"),
            tableOutput("optParTable_Omega")
        )
    ),
    column(width = 4,
        box(width = NULL,
            status = "primary",
            solidHeader = TRUE,
            title = "Parameter Selection",
            p("The optimisation algorithm takes six model parameters representing six hypothetical interventions and simulates the cost and impact of all permutations."),
            helpText("For each intervention, select the number of parameter values to simulate and set the range of rates to sample from (rates are uniformally distributed within this range).
                The parameter values for each intervention are then displayed in the corresponding tables."),
            bsButton("resetSliders", label = "RESET SLIDERS", block = TRUE, style = "danger"),
            p(" "),
            helpText("Below is the number of iterations the model will simulate along with the estimated time to completion. Hit the 'OPTIMISE' button to begin the simulation. Note the progress bar
                at the top of the screen, and the run number and elapsed time on the top right. Please wait until the optimisation algorithm has completed the below bar has turned green before proceeding to the results tab."),
            bsButton("optimiseInput", label = "OPTIMISE", block = TRUE, size = "large", style = "primary"),
            bsTooltip(id = "optimiseInput", title = "Wait for progress bar to complete before proceeding.", placement = "right", trigger = "hover"),
            p(" "),
            tableOutput("optIterationTable"),
            bsButton("optFinished", label = "OPTIMISATION NOT RUN", style = "danger", block = TRUE, icon = icon("ban", class = "fa-lg fa-fw", lib = "font-awesome"), disabled = TRUE)
        ),
        bsButton(inputId = "goToWizard2", label = "Return", style = "primary", size = "large", block = TRUE, icon = icon("backward", class = "fa-lg fa-fw", lib = "font-awesome"))
    )
)
