tabItem(tabName = "opt-parameter",
    column(width = 8,
        shinyjs::useShinyjs(),
        id = "optimisation-panel",
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            title = "HIV-Testing (rho)",
            helpText("by varying diagnosis rate, rho"),
            sliderInput('userOptRho_LengthOf','Length of parameter range:', min = 0, max = 10, value = 1, step = 1),
            sliderInput('userOptRho_Range','Range of values (diagnoses/py):', min = 0, max = 50, value = c(0.205, 20), step = 0.001),
            tableOutput("optParTable_Rho")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            title = "Linkage (epsilon)",
            helpText("by varying care seeking rate, epsilon"),
            sliderInput('userOptEpsilon_LengthOf','Length of parameter range:', min = 0, max = 10, value = 1, step=1),
            sliderInput('userOptEpsilon_Range','Range of values (persons seeking care/py):', min = 0, max = 50, value = c(16.949, 30), step = 0.001),
            tableOutput("optParTable_Epsilon")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            title = "Pre-ART Retention (kappa)",
            helpText("by varying pre-ART dropout rate, kappa"),
            sliderInput('userOptKappa_LengthOf','Length of parameter range:', min = 0, max = 10, value = 1, step = 1),
            sliderInput('userOptKappa_Range','Range of values (person lost from pre-ART care/py):', min = 0, max = 2, value = c(0.01, 1.079), step = 0.001),
            tableOutput("optParTable_Kappa")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            title = "Treatment Initiation (gamma)",
            helpText("by varying ART initiation rate, gamma"),
            sliderInput('userOptGamma_LengthOf','Length of parameter range:', min = 0, max = 10, value = 1, step = 1),
            sliderInput('userOptGamma_Range','Range of values (ART initiations/py):', min = 0, max = 50, value = c(2.556, 20), step = 0.001),
            tableOutput("optParTable_Gamma")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            title = "Adherence (sigma)",
            helpText("by varying rate at which patients not adhering to treatment start to adhere, sigma"),
            sliderInput('userOptSigma_LengthOf','Length of parameter range:', min = 0, max = 10, value = 4, step = 1),
            sliderInput('userOptSigma_Range','Range of values (persons transitioning from non-adherent to adherent/py):', min = 0, max = 1, value = c(0, 1), step = 0.001),
            tableOutput("optParTable_Sigma")
        ),
        box(width = NULL,
            height = '100%',
            status = "warning",
            solidHeader = TRUE,
            title = "ART Retention (omega)",
            helpText("by varying rate at which patients are lost from ART care, omega"),
            sliderInput('userOptOmega_LengthOf','Length of parameter range:', min = 0, max = 10, value = 4, step = 1),
            sliderInput('userOptOmega_Range','Range of values (ART dropout/py):', min = 0, max = 0.1, value = c(-0.1, 0.033), step = 0.001),
            tableOutput("optParTable_Omega")
        )
    ),
    column(width = 4,
        box(width = NULL,
            status = "primary",
            solidHeader = TRUE,
            title = "Parameter Selection",
            p("The optimisation algorithm takes six model parameters representing six hypothetical interventions and simulates the cost and impact of all permutations."),
            helpText("For each intervention, select the number of parameter values to simulate and set the range of rates to sample from (rates are uniformally distributed within this range).
                The parameter values for each intervention are then displayed in the corresponding tables."),
            bsButton("resetSliders", label = "RESET SLIDERS", block = TRUE, style = "danger"),
            p(" "),
            helpText("Below is the number of iterations the model will simulate along with the estimated time to completion. Hit the 'OPTIMISE' button to begin the simulation. Note the progress bar
                at the top of the screen, and the run number and elapsed time on the top right. Please wait until the optimisation algorithm has completed the below bar has turned green before proceeding to the results tab."),
            bsButton("optimiseInput", label = "OPTIMISE", block = TRUE, size = "large", style = "primary"),
            bsTooltip(id = "optimiseInput", title = "Wait for progress bar to complete before proceeding.", placement = "right", trigger = "hover"),
            p(" "),
            tableOutput("optIterationTable"),
            bsButton("optFinished", label = "OPTIMISATION NOT RUN", style = "danger", block = TRUE, icon = icon("ban", class = "fa-lg fa-fw", lib = "font-awesome"), disabled = TRUE)
        ),
        bsButton(inputId = "wizardOpt_3", label = "Next", style = "success", size = "large", block = TRUE, icon = icon("arrow-right", class = "fa-lg fa-fw", lib = "font-awesome"))
    )
)
